version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

jobs:
  test_app:
    docker:
      - image: circleci/node:9.11.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "pull submodules"
          command: |
            git submodule init
            git submodule update --recursive
      - run:
          name: "run test"
          command: |
            cd submodules/goof
            npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  build_image:
    docker:
      - image: circleci/node:9.11.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - aws-ecr/build-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          dockerfile: Dockerfile
          path: ./submodules/goof/
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: 'latest,${CIRCLE_BUILD_NUM}'

  push_image:
    docker:
      - image: circleci/node:9.11.2
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - aws-ecr/ecr-login:
          region: AWS_REGION_ENV_VAR_NAME
      - aws-ecr/push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: 'latest,${CIRCLE_BUILD_NUM}'

workflows:
  build_and_deploy:
    jobs:
      - test_app
      - build_image:
          requires:
            - test_app
      - push_image:
          requires:
            - build_image
