version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

workflows:
  build_and_push_image:
    jobs:
      - build_test
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          repo: ${CIRCLE_PROJECT_REPONAME}
          create-repo: true
          checkout: true
          dockerfile: Dockerfile
          path: ./submodules/goof/
          tag: 'latest,${CIRCLE_BUILD_NUM}'
          requirements:
            build_test

jobs:
  build_test:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run:
          name: "pull submodules"
          command: |
            git submodule init
            git submodule update --recursive
      - run:
          name: "run test"
          command: |
            cd submodule/goof
            mongod &
            npm insall
            npm start