apiVersion: v1
kind: Service
metadata:
  name: goof
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
    name: "http"
  - protocol: TCP
    port: 9229
    targetPort: 9229
    name: "9229"
  selector:
    app: goof
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: goof-mongo
<<<<<<< HEAD
<<<<<<< HEAD
=======
  name: goof
>>>>>>> fbce702... add tier to manifests
  labels:
    app: goof
=======
>>>>>>> 0325ad3... change labels
=======
>>>>>>> b469795afbee389d53bbba065b35dbf1b7b82640
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: goof
    tier: backend
