apiVersion: v1
kind: Service
metadata:
  labels:
    name: goof
  name: goof
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  - protocol: TCP
    port: 9229
    targetPort: 9229
  selector:
    app: goof
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo
