apiVersion: v1
kind: Service
metadata:
  name: goof
  labels:
    app: goof
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
    name: "http"
  - protocol: TCP
    port: 9229
    targetPort: 9229
    name: "9229"
  selector:
    app: goof
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: goof-mongo
=======
  name: goof
>>>>>>> 8c6e40b37414f04052310935e0f696e1a143f64e
  labels:
    app: goof
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: goof
    tier: backend
