apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
  labels:
    app: goof
spec:
  selector:
    matchLabels:
      app: goof
  replicas: 3
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
        - name: goof
          image: DOCKER_IMAGE_NAME
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: VERSION_INFO
              value: "VERSION_INFO_VALUE"
            - name: BUILD_DATE
              value: "BUILD_DATE_VALUE"
          ports:
            - containerPort: 3001