apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
  labels:
    app: goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
        - name: goof
          image: DOCKER_IMAGE_NAME
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3001
            - containerPort: 9229
          env:
            - name: DOCKER
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-mongo
  labels:
    app: goof-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof-mongo
  template:
    metadata:
      labels:
        app: goof-mongo
    spec:
      containers:
        - name: goof-mongo
          image: mongo
          ports:
            - containerPort: 27017